### PR TITLE
API Use ShortName of class instead of FQN for body class property

### PR DESCRIPTION
**Pull request by tractorcow**
Fixes https://github.com/silverstripe/silverstripe-framework/issues/7586

Merge with https://github.com/silverstripe/silverstripe-framework/pull/7600

### CODE REVIEW

**Comment by tractorcow** [comment]
Responded at https://github.com/silverstripe/silverstripe-framework/issues/7586#issuecomment-344065036

**Comment by flamerohr** [comment]
Neat :D could it be a part of this?

**Comment by dhensby** [comment]
Does `$ClassName.ATT` provide a correctly escaped value?

**Comment by tractorcow** [comment]
@dhensby it's not an issue of escaping; It generates ATT-safe string, but a non-css valid class name.

**Pull request merged**
